
package com.barberia.citaShow.response;

import lombok.*;
import lombok.experimental.FieldDefaults;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class AddresResponse {
	private Long id;
	private String latitude;
	private String length;
	private String street;
	private String race;
	private String neighborhood;
	private String address;
	private String description;
	private ProvidersResponse providers;

}
