
package com.barberia.citaShow.response;

import lombok.*;
import lombok.experimental.FieldDefaults;

import java.sql.Timestamp;
import java.time.LocalDate;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class AppointmentResponse {
	private Long id;
	private Timestamp appointmentDate;
	private Boolean postpones;
	private int turn;
	private ProvidersResponse providers;
	private ServiceResponse services;
	private UsersResponse users;
	private EmployeeResponse employee;

}
