
package com.barberia.citaShow.response;

import java.util.List;

import lombok.*;
import lombok.experimental.FieldDefaults;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class ServiceResponse {

	private Long id;
	private Long serviceTime;
	private String name;
	private String img;
	private String description;
	private Long price;
	private ProvidersResponse providers;
	private List<AppointmentResponse> appointment;
	private TypeOfServiceResponse typeOfService;
}
