
package com.barberia.citaShow.response;

import lombok.*;
import lombok.experimental.FieldDefaults;

import java.time.LocalDate;
import java.util.Collection;
import java.util.List;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class UsersResponse {
	private Long id;
	private String name;
	private String email;
	private String username;

	private String nickname;
	private String lastname;
	private LocalDate birth;

	private boolean typespolitics;
	private boolean locked;
	private boolean politics;

	private List<RoleResponse> role;
	private EmployeeResponse employee;
	private List<ProvidersResponse> providers;
	private List<AppointmentResponse> appointment;
}
