package com.barberia.citaShow.dto;

import java.sql.Timestamp;

import java.io.Serializable;
import java.util.List;

import com.barberia.citaShow.entity.AddresEntity;
import com.barberia.citaShow.entity.AppointmentEntity;
import com.barberia.citaShow.entity.UsersEntity;
import com.barberia.citaShow.request.CreateAddresRequest;
import com.barberia.citaShow.request.CreateAppointmentRequest;
import com.barberia.citaShow.request.CreateEmployeeRequest;
import com.barberia.citaShow.request.CreateUsersRequest;
import jakarta.persistence.OneToMany;
import lombok.*;
import lombok.experimental.FieldDefaults;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class ProvidersDto {
	private Long id;
	private String name;
	private Long nit;
	private String invima;
	private String openDate;
	private String closeDate;
	private String ownerId;
	private UsersDto users;
	private List<AppointmentDto> appointment;
	private List<AddresDto> addres;

	private List<EmployeeDto> employee;
}
