package com.barberia.citaShow.dto;

import java.util.List;

import com.barberia.citaShow.request.CreateUsersRequest;
import lombok.*;
import lombok.experimental.FieldDefaults;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class RoleDto {

	private Long id;
	private String name;
	private String description;
	private boolean state;
}
