package com.barberia.citaShow.dto;
import java.sql.Timestamp;
import java.util.List;

import com.barberia.citaShow.entity.AppointmentEntity;
import lombok.*;
import lombok.experimental.FieldDefaults;

/**
*Code generated by The Carpenter from softcaribbean
* Date:<CURRENT_DATE>
*/
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class ServiceDto {

	private Long id;
	private Long serviceTime;
	private String name;
	private String img;
	private String description;
	private Long price;
	private ProvidersDto providers;
	private List<AppointmentDto> appointment;
	private TypeOfServiceDto typeOfService;
}



