
package com.barberia.citaShow.dto;

import com.barberia.citaShow.dto.RoleDto;
import com.barberia.citaShow.request.CreateAppointmentRequest;
import com.barberia.citaShow.request.CreateEmployeeRequest;
import com.barberia.citaShow.request.CreateProvidersRequest;
import com.barberia.citaShow.request.CreateRoleRequest;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.time.LocalDate;
import java.util.Collection;
import java.util.List;

/**
 * Code generated by The Carpenter from softcaribbean
 * Date:<CURRENT_DATE>
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
@Setter
@Getter
@RequiredArgsConstructor

public class UsersDto {
	private Long id;
	private String name;
	private String email;
	private String username;

	private String nickname;
	private String lastname;
	private LocalDate birth;

	private boolean typespolitics;
	private boolean locked;
	private boolean politics;

	private List<RoleDto> role;
	private EmployeeDto employee;
	private List<ProvidersDto> providers;
	private List<AppointmentDto> appointment;
}
