package com.barberia.citaShow.entity;


import java.io.Serializable;
import java.sql.Timestamp;

import lombok.*;

import jakarta.persistence.*;
/**
*Code generated by The Carpenter from softcaribbean
*/

@Setter
@Getter
@RequiredArgsConstructor
@Table(name = "addres")
@Entity

public class AddresEntity implements Serializable {
    
    private static final long serialVersionUID = 1L;


    @Id
	@GeneratedValue( strategy=GenerationType.IDENTITY  )
	@Column( nullable=false   )
	private Long id;

	@Column( nullable=true  )
	private String latitude;

	@Column( nullable=true  )
	private String length ;

	@Column( nullable=true  )
	private String street;

	@Column( nullable=true  )
	private String race;

	@Column( nullable=true  )
	private String neighborhood;

	@Column( nullable=true  )
	private String address;

	@Column( nullable=true  )
	private String description;

	@ManyToOne
	@JoinColumn(name = "id_providers")
	private ProvidersEntity providers;


	@Column(name = "created_at")
	private Timestamp createdAt;

	@Column(name = "updated_at")
	private Timestamp updatedAt;

	@Column(name = "deleted_at")
	private Timestamp deletedAt;


	@PrePersist
	public void createdAtInsert() {

		this.createdAt = new Timestamp(System.currentTimeMillis());;
	}
	@PreUpdate
	public  void updatedAt(){
		this.updatedAt = new Timestamp(System.currentTimeMillis());;
	}

	@PreRemove
	public  void  deletedAt(){
		this.deletedAt = new Timestamp(System.currentTimeMillis());;
	}
}



