package com.barberia.citaShow.entity;


import java.io.Serializable;
import java.sql.Timestamp;
import java.time.LocalDate;

import lombok.*;
import jakarta.persistence.*;
/**
*Code generated by The Carpenter from softcaribbean
*/

@Setter
@Getter
@RequiredArgsConstructor
@Table(name = "appointment")
@Entity

public class AppointmentEntity implements Serializable {
    
    private static final long serialVersionUID = 1L;


    @Id
	@GeneratedValue( strategy=GenerationType.IDENTITY  )
	@Column( nullable=false  )
	private Long id;

	@Column( nullable=true  )
	private Timestamp appointmentDate;

	@Column( nullable=true  )
	private Boolean postpones;

	@Column( nullable=true  )
	private int turn;

	@ManyToOne()
	@JoinColumn(name = "id_users")
	private UsersEntity users;

	@ManyToOne
	@JoinColumn(name = "id_providers")
	private ProvidersEntity providers;


	@ManyToOne
	@JoinColumn(name = "id_service")
	private ServiceEntity services;

	@ManyToOne
	@JoinColumn(name = "id_employee")
	private EmployeeEntity employee;

	@Column(name = "created_at")
	private Timestamp createdAt;

	@Column(name = "updated_at")
	private Timestamp updatedAt;

	@Column(name = "deleted_at")
	private Timestamp deletedAt;

	@PrePersist
	public void createdAtInsert() {

		this.createdAt = new Timestamp(System.currentTimeMillis());;
	}
	@PreUpdate
	public  void updatedAt(){
		this.updatedAt = new Timestamp(System.currentTimeMillis());;
	}

	@PreRemove
	public  void  deletedAt(){
		this.deletedAt = new Timestamp(System.currentTimeMillis());;
	}
}



