package com.barberia.citaShow.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import lombok.*;
import jakarta.persistence.*;
/**
*Code generated by The Carpenter from softcaribbean
*/

@Setter
@Getter
@RequiredArgsConstructor
@Table(name = "role")
@Entity

public class RoleEntity implements Serializable {
    
    private static final long serialVersionUID = 1L;


    @Id
	@GeneratedValue( strategy=GenerationType.IDENTITY  )
	@Column( nullable=false  )
	private Long id;
	@Column( nullable=true  )
	private String name;
	@Column( nullable=true  )
	private String description;
	@Column( nullable=true  )
	private boolean state;

	@ManyToMany
	@JoinTable(name = "roles_users", joinColumns = @JoinColumn(name = "id_role"), inverseJoinColumns = @JoinColumn(name = "id_users"))
	private List<UsersEntity> users ;

	@Column(name = "created_at")
	private Timestamp createdAt;

	@Column(name = "updated_at")
	private Timestamp updatedAt;

	@Column(name = "deleted_at")
	private Timestamp deletedAt;

	@PrePersist
	public void createdAtInsert() {

		this.createdAt = new Timestamp(System.currentTimeMillis());;
	}
	@PreUpdate
	public  void updatedAt(){
		this.updatedAt = new Timestamp(System.currentTimeMillis());;
	}

	@PreRemove
	public  void  deletedAt(){
		this.deletedAt = new Timestamp(System.currentTimeMillis());;
	}
}



