package com.barberia.citaShow.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;

import lombok.*;

import jakarta.persistence.*;

/**
*Code generated by The Carpenter from softcaribbean
*/

@Setter
@Getter
@RequiredArgsConstructor
@Table(name = "service")
@Entity

public class ServiceEntity implements Serializable {
    
    private static final long serialVersionUID = 1L;


    @Id
	@GeneratedValue( strategy=GenerationType.IDENTITY  )
	@Column( nullable=false  )
	private Long id;
	@Column( nullable=true  )
	private Long serviceTime;
	@Column( nullable=true  )
	private String name;
	@Column( nullable=true  )
	private String img;
	@Column( nullable=true  )
	private String description;
	@Column( nullable=true  )
	private Long price;

	@OneToMany(mappedBy = "services")
	private List<AppointmentEntity> appointment;


	@ManyToOne
	@JoinColumn(name = "id_providers")
	private ProvidersEntity providers;

	@ManyToOne
	@JoinColumn(name = "id_typeOfService")
	private TypeOfServiceEntity typeOfService;


	@Column(name = "created_at")
	private Timestamp createdAt;

	@Column(name = "updated_at")
	private Timestamp updatedAt;

	@Column(name = "deleted_at")
	private Timestamp deletedAt;

	@PrePersist
	public void createdAtInsert() {

		this.createdAt = new Timestamp(System.currentTimeMillis());;
	}
	@PreUpdate
	public  void updatedAt(){
		this.updatedAt = new Timestamp(System.currentTimeMillis());;
	}

	@PreRemove
	public  void  deletedAt(){
		this.deletedAt = new Timestamp(System.currentTimeMillis());;
	}
}



